apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: map-query-api
  annotations:
    version: v0.0.1
    description: "Takes in a query from map-cli, adds an id, then further sends to a interest based workqueue for further handling"
spec:
  policies:
    - name: nats-kv
      type: policy.secret.wasmcloud.dev/v1alpha1
      properties:
        backend: nats-kv
  components:
    - name: map-query-api
      type: component
      properties:
        image: ghcr.io/mattilsynet/map-query-api:v0.0.5-pre-3
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target:
              name: map-jetstream-nats
              secrets:
                - name: nats-credentials
                  properties:
                    policy: nats-kv
                    key: map-query-api-nats-credentials
              config:
                - name: nats-jetstream-config
                  properties:
                    url: "nats://connect.nats.mattilsynet.io"
            namespace: mattilsynet
            package: provider-jetstream-nats
            interfaces: [jetstream-publish]
        - type: link
          properties:
            target: nats-core
            target_config:
                - name: nats-core-config
                  properties:
                    cluster_uris: "nats://connect.nats.mattilsynet.io"
                    client_seed: ""
                    client_jwt: ""
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]
    - name: map-jetstream-nats
      type: capability
      properties:
        image: ghcr.io/mattilsynet/map-nats-jetstream:v0.0.1-pre-17
    - name: nats-core
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:canary
        config:
          - name: nats-core-subject-root
            properties:
              cluster_uris: "nats://connect.nats.mattilsynet.io"
              subscriptions: map.get
              client_jwt: ""
              client_seed: ""
      traits:
        - type: link
          properties:
            target:
              name: map-query-api
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source:
              config:
                - name: nats-core-subject-config
                  properties:
                    cluster_uris: "nats://connect.nats.mattilsynet.io"
                    subscriptions: map.get
                    client_seed: ""
                    client_jwt: ""
