apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: map-query-api
  annotations:
    version: v0.0.1
    description: "Takes in a command from map-cli, adds an id, then further sends to a interest based workqueue for further handling"
spec:
  components:
    - name: map-query-api
      type: component
      properties:
        image: ghcr.io/mattilsynet/map-query-api:v0.0.5.4
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target:
              name: map-jetstream-nats
              config:
                - name: nats-config
                  properties:
                    url: "nats://localhost:4222"
            namespace: mattilsynet
            package: map-nats-jetstream
            interfaces: [jetstream-publish]
        - type: link
          properties:
            target: nats-core
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]

    - name: map-jetstream-nats
      type: capability
      properties:
        #        image: file://./../map-nats-jetstream/build/map-jetstream-nats.par.gz
        image: ghcr.io/Mattilsynet/map-nats-jetstream:v0.0.1.28

    - name: nats-core
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:canary
      traits:
        - type: spreadscalar
          properties:
            instances: 1
        - type: link
          properties:
            target: map-query-api
            namespace: mattilsynet
            package: provider-jetstream-nats
            interfaces: [handler]
            source:
              config:
                - name: map-query-api-subject
                  properties:
                    subscriptions: map.get
