apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: map-query-api
  annotations:
    version: v0.0.1
    description: 'Takes in a command from map-cli, adds an id, then further sends to a interest based workqueue for further handling'
    authors: Mattilsynet Plattform team
spec:
  components:
    - name: map-query-api
      type: component
      properties:
        image: file://./build/map-query-api_s.wasm
        #image: ghcr.io/wasmcloud/components/echo-messaging-rust:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]
            #TODO: This needs to be different as we're going to handle different subjects than map-command-api
        - type: link    
          properties:
            target: map-jetstream-nats
            namespace: mattilsynet
            package: provider-jetstream-nats
            interfaces: [jetstream-publish]
            target_config:
              - name: nats-config
                properties:
                  jwt: ""
                  seed: ""
                  url: "nats://localhost:4222"
    - name: map-jetstream-nats
      type: capability
      properties:
        image: file://./../map-nats-jetstream/build/map-jetstream-nats.par.gz
    - name: nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:canary
      traits:
        - type: spreadscalar
          properties:
            replicas: 1
        - type: link
          properties:
            target: map-query-api
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source_config:
              - name: map-query-api-subject
                properties:
                  subscriptions: map.get
 
