name = "map-query-api"
language = "tinygo"
type = "component"
version = "0.1.0"

[component]
wit_world = "map-query-api"
wasm_target = "wasm32-wasi-preview2"
destination = "build/map-query-api_s.wasm"
