name: build_push

on:
  push:
    branches:
      - master
      
jobs:
  wash-build:
    runs-on: ubuntu-latest
    env:
      built_file_name: map-query-api_s.wasm
    permissions:
     contents: 'write'
    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: install go
       uses: actions/setup-go@v2
     - name: install tinygo
       uses: acifani/setup-tinygo@v2
       with:
         install-binaryen: 'false'
     - name: install wash tools
       uses: taiki-e/install-action@v2
       with:
         tool: wit-bindgen-cli, wasm-tools
     - name: install wash-cli cached
       uses: taiki-e/cache-cargo-install-action@v2
       with:
         tool: wash-cli
     - name: pwd 
       shell: bash
       run: |
          pwd
          cd build
          pwd
     - name: validate-yaml
       shell: bash
       run: |
          [[ ! -f wadm.yaml ]] || wash app validate wadm.yaml
          [[ ! -f local.wadm.yaml ]] || wash app validate local.wadm.yaml
     - name: publish package to github repository 
       shell: bash
       run: |
          wash push ghcr.io/${{ github.repository }}:${{ github.ref_name }} ${{ env.built_file_name }} --annotation org.opencontainers.image.source=${{github.server_url}}/${{ github.repository }}


#TODO: run wash up, wash apply and check output for success messages
      
            
